DELETE FROM "FORMULAIRE"."REVINFO";
DELETE FROM "FORMULAIRE"."TA_DONNEE";
DELETE FROM "FORMULAIRE"."TA_SAISIE";
DELETE FROM "FORMULAIRE"."TA_CHAMP";
DELETE FROM "FORMULAIRE"."TA_FORMULAIRE";
DELETE FROM "FORMULAIRE"."TA_DESCRIPTION_CHAMP";
COMMIT;
DROP SEQUENCE "FORMULAIRE"."REVINFO_SEQ";
CREATE SEQUENCE  "FORMULAIRE"."REVINFO_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 CACHE 5;