DROP TABLE "FORMULAIRE"."TA_DONNEE";
DROP TABLE "FORMULAIRE"."TA_SAISIE";
DROP TABLE "FORMULAIRE"."TA_CHAMP";
DROP TABLE "FORMULAIRE"."TA_FORMULAIRE";
DROP TABLE "FORMULAIRE"."TA_DESCRIPTION_CHAMP";

CREATE TABLE "FORMULAIRE"."TA_DESCRIPTION_CHAMP" (
	-- Identification
	"IDENTIFIANT" VARCHAR2(36 BYTE) NOT NULL ENABLE, 

	"CODE" VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"LIBELLE" VARCHAR2(255 BYTE) NOT NULL ENABLE,
	
	-- Audit
	 "AUDIT_IDENTIFIANT" VARCHAR2(36 BYTE) NOT NULL ENABLE,
	 "AUDIT_ACTEUR" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	 "AUDIT_FONCTIONNALITE" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	 "AUDIT_ACTION" VARCHAR2(12 BYTE) NOT NULL ENABLE,
	 "AUDIT_DATE" DATE NOT NULL ENABLE,
	 "AUDIT_SESSION" VARCHAR2(36 BYTE),
	 
	-- Constraints
	CONSTRAINT "TA_DESCRIPTION_CHAMP_PK" PRIMARY KEY ("IDENTIFIANT") ENABLE,
	CONSTRAINT "TA_DESCRIPTION_CHAMP_UK1" UNIQUE ("CODE")
);
COMMENT ON TABLE "FORMULAIRE"."TA_DESCRIPTION_CHAMP" IS 'Table des descriptions de champs';
COMMENT ON COLUMN "FORMULAIRE"."TA_DESCRIPTION_CHAMP"."IDENTIFIANT" IS 'Identifiant de la description de champ';
COMMENT ON COLUMN "FORMULAIRE"."TA_DESCRIPTION_CHAMP"."CODE" IS 'Code de la description de champ';
COMMENT ON COLUMN "FORMULAIRE"."TA_DESCRIPTION_CHAMP"."LIBELLE" IS 'Libellé de la description de champ';
COMMENT ON COLUMN "FORMULAIRE"."TA_DESCRIPTION_CHAMP"."AUDIT_IDENTIFIANT" IS 'Identifiant de l''audit';
COMMENT ON COLUMN "FORMULAIRE"."TA_DESCRIPTION_CHAMP"."AUDIT_ACTEUR" IS 'Qui a fait';
COMMENT ON COLUMN "FORMULAIRE"."TA_DESCRIPTION_CHAMP"."AUDIT_FONCTIONNALITE" IS 'La fonctionnalité faite';
COMMENT ON COLUMN "FORMULAIRE"."TA_DESCRIPTION_CHAMP"."AUDIT_ACTION" IS 'Quoi a été fait sur la donnée';
COMMENT ON COLUMN "FORMULAIRE"."TA_DESCRIPTION_CHAMP"."AUDIT_DATE" IS 'Quand cela a été fait';
COMMENT ON COLUMN "FORMULAIRE"."TA_DESCRIPTION_CHAMP"."AUDIT_SESSION" IS 'Dans quelle session cela a été fait';

CREATE TABLE "FORMULAIRE"."TA_FORMULAIRE" (
	-- Identification
	"IDENTIFIANT" VARCHAR2(36 BYTE) NOT NULL ENABLE, 

	"CODE" VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"LIBELLE" VARCHAR2(255 BYTE) NOT NULL ENABLE,
	
	-- Audit
	 "AUDIT_IDENTIFIANT" VARCHAR2(36 BYTE) NOT NULL ENABLE,
	 "AUDIT_ACTEUR" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	 "AUDIT_FONCTIONNALITE" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	 "AUDIT_ACTION" VARCHAR2(12 BYTE) NOT NULL ENABLE,
	 "AUDIT_DATE" DATE NOT NULL ENABLE,
	 "AUDIT_SESSION" VARCHAR2(36 BYTE),
	 
	-- Constraints
	CONSTRAINT "TA_FORMULAIRE_PK" PRIMARY KEY ("IDENTIFIANT") ENABLE,
	CONSTRAINT "TA_FORMULAIRE_UK1" UNIQUE ("CODE")
);
COMMENT ON TABLE "FORMULAIRE"."TA_FORMULAIRE" IS 'Table des formulaires';
COMMENT ON COLUMN "FORMULAIRE"."TA_FORMULAIRE"."IDENTIFIANT" IS 'Identifiant du formulaire';
COMMENT ON COLUMN "FORMULAIRE"."TA_FORMULAIRE"."CODE" IS 'Code du formulaire';
COMMENT ON COLUMN "FORMULAIRE"."TA_FORMULAIRE"."LIBELLE" IS 'Libellé du formulaire';
COMMENT ON COLUMN "FORMULAIRE"."TA_FORMULAIRE"."AUDIT_IDENTIFIANT" IS 'Identifiant de l''audit';
COMMENT ON COLUMN "FORMULAIRE"."TA_FORMULAIRE"."AUDIT_ACTEUR" IS 'Qui a fait';
COMMENT ON COLUMN "FORMULAIRE"."TA_FORMULAIRE"."AUDIT_FONCTIONNALITE" IS 'La fonctionnalité faite';
COMMENT ON COLUMN "FORMULAIRE"."TA_FORMULAIRE"."AUDIT_ACTION" IS 'Quoi a été fait sur la donnée';
COMMENT ON COLUMN "FORMULAIRE"."TA_FORMULAIRE"."AUDIT_DATE" IS 'Quand cela a été fait';
COMMENT ON COLUMN "FORMULAIRE"."TA_FORMULAIRE"."AUDIT_SESSION" IS 'Dans quelle session cela a été fait';

CREATE TABLE "FORMULAIRE"."TA_CHAMP" (
	-- Identification
	"IDENTIFIANT" VARCHAR2(36 BYTE) NOT NULL ENABLE, 

	"FORMULAIRE" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(36 BYTE) NOT NULL ENABLE,
	
	-- Audit
	 "AUDIT_IDENTIFIANT" VARCHAR2(36 BYTE) NOT NULL ENABLE,
	 "AUDIT_ACTEUR" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	 "AUDIT_FONCTIONNALITE" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	 "AUDIT_ACTION" VARCHAR2(12 BYTE) NOT NULL ENABLE,
	 "AUDIT_DATE" DATE NOT NULL ENABLE,
	 "AUDIT_SESSION" VARCHAR2(36 BYTE),
	 
	-- Constraints
	CONSTRAINT "TA_CHAMP_PK" PRIMARY KEY ("IDENTIFIANT") ENABLE,
	CONSTRAINT "TA_CHAMP_FK1" FOREIGN KEY ("FORMULAIRE") REFERENCES "TA_FORMULAIRE" ("IDENTIFIANT") ENABLE,
	CONSTRAINT "TA_CHAMP_FK2" FOREIGN KEY ("DESCRIPTION") REFERENCES "TA_DESCRIPTION_CHAMP" ("IDENTIFIANT") ENABLE,
	CONSTRAINT "TA_CHAMP_UK1" UNIQUE ("FORMULAIRE","DESCRIPTION") ENABLE
);
COMMENT ON TABLE "FORMULAIRE"."TA_CHAMP" IS 'Table des champs';
COMMENT ON COLUMN "FORMULAIRE"."TA_CHAMP"."IDENTIFIANT" IS 'Identifiant du champ';
COMMENT ON COLUMN "FORMULAIRE"."TA_CHAMP"."FORMULAIRE" IS 'Identifiant du formulaire';
COMMENT ON COLUMN "FORMULAIRE"."TA_CHAMP"."DESCRIPTION" IS 'Identifiant de la description de champ';
COMMENT ON COLUMN "FORMULAIRE"."TA_CHAMP"."AUDIT_IDENTIFIANT" IS 'Identifiant de l''audit';
COMMENT ON COLUMN "FORMULAIRE"."TA_CHAMP"."AUDIT_ACTEUR" IS 'Qui a fait';
COMMENT ON COLUMN "FORMULAIRE"."TA_CHAMP"."AUDIT_FONCTIONNALITE" IS 'La fonctionnalité faite';
COMMENT ON COLUMN "FORMULAIRE"."TA_CHAMP"."AUDIT_ACTION" IS 'Quoi a été fait sur la donnée';
COMMENT ON COLUMN "FORMULAIRE"."TA_CHAMP"."AUDIT_DATE" IS 'Quand cela a été fait';
COMMENT ON COLUMN "FORMULAIRE"."TA_CHAMP"."AUDIT_SESSION" IS 'Dans quelle session cela a été fait';

CREATE TABLE "FORMULAIRE"."TA_SAISIE" (
	-- Identification
	"IDENTIFIANT" VARCHAR2(36 BYTE) NOT NULL ENABLE, 

	"FORMULAIRE" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	
	-- Audit
	 "AUDIT_IDENTIFIANT" VARCHAR2(36 BYTE) NOT NULL ENABLE,
	 "AUDIT_ACTEUR" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	 "AUDIT_FONCTIONNALITE" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	 "AUDIT_ACTION" VARCHAR2(12 BYTE) NOT NULL ENABLE,
	 "AUDIT_DATE" DATE NOT NULL ENABLE,
	 "AUDIT_SESSION" VARCHAR2(36 BYTE),
	 
	-- Constraints
	CONSTRAINT "TA_SAISIE_PK" PRIMARY KEY ("IDENTIFIANT") ENABLE,
	CONSTRAINT "TA_SAISIE_FK1" FOREIGN KEY ("FORMULAIRE") REFERENCES "TA_FORMULAIRE" ("IDENTIFIANT") ENABLE
);
COMMENT ON TABLE "FORMULAIRE"."TA_SAISIE" IS 'Table des saisies';
COMMENT ON COLUMN "FORMULAIRE"."TA_SAISIE"."IDENTIFIANT" IS 'Identifiant de saisie';
COMMENT ON COLUMN "FORMULAIRE"."TA_SAISIE"."FORMULAIRE" IS 'Identifiant du formulaire';
COMMENT ON COLUMN "FORMULAIRE"."TA_SAISIE"."AUDIT_IDENTIFIANT" IS 'Identifiant de l''audit';
COMMENT ON COLUMN "FORMULAIRE"."TA_SAISIE"."AUDIT_ACTEUR" IS 'Qui a fait';
COMMENT ON COLUMN "FORMULAIRE"."TA_SAISIE"."AUDIT_FONCTIONNALITE" IS 'La fonctionnalité faite';
COMMENT ON COLUMN "FORMULAIRE"."TA_SAISIE"."AUDIT_ACTION" IS 'Quoi a été fait sur la donnée';
COMMENT ON COLUMN "FORMULAIRE"."TA_SAISIE"."AUDIT_DATE" IS 'Quand cela a été fait';
COMMENT ON COLUMN "FORMULAIRE"."TA_SAISIE"."AUDIT_SESSION" IS 'Dans quelle session cela a été fait';

CREATE TABLE "FORMULAIRE"."TA_DONNEE" (
	-- Identification
	"IDENTIFIANT" VARCHAR2(36 BYTE) NOT NULL ENABLE, 

	"SAISIE" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	"CHAMP" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	
	"CHAINE_CARACTERES" VARCHAR2(1024 BYTE), 
	"NOMBRE_ENTIER" NUMBER(19,0), 
	
	-- Audit
	 "AUDIT_IDENTIFIANT" VARCHAR2(36 BYTE) NOT NULL ENABLE,
	 "AUDIT_ACTEUR" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	 "AUDIT_FONCTIONNALITE" VARCHAR2(64 BYTE) NOT NULL ENABLE,
	 "AUDIT_ACTION" VARCHAR2(12 BYTE) NOT NULL ENABLE,
	 "AUDIT_DATE" DATE NOT NULL ENABLE,
	 "AUDIT_SESSION" VARCHAR2(36 BYTE),
	 
	-- Constraints
	CONSTRAINT "TA_DONNEE_PK" PRIMARY KEY ("IDENTIFIANT") ENABLE,
	CONSTRAINT "TA_DONNEE_FK1" FOREIGN KEY ("SAISIE") REFERENCES "TA_SAISIE" ("IDENTIFIANT") ENABLE,
	CONSTRAINT "TA_DONNEE_FK2" FOREIGN KEY ("CHAMP") REFERENCES "TA_CHAMP" ("IDENTIFIANT") ENABLE,
	CONSTRAINT "TA_DONNEE_UK1" UNIQUE ("SAISIE","CHAMP") ENABLE
);
COMMENT ON TABLE "FORMULAIRE"."TA_DONNEE" IS 'Table des données';
COMMENT ON COLUMN "FORMULAIRE"."TA_DONNEE"."IDENTIFIANT" IS 'Identifiant de la donnée';
COMMENT ON COLUMN "FORMULAIRE"."TA_DONNEE"."SAISIE" IS 'Identifiant de la saisie';
COMMENT ON COLUMN "FORMULAIRE"."TA_DONNEE"."CHAMP" IS 'Identifiant du champ';
COMMENT ON COLUMN "FORMULAIRE"."TA_DONNEE"."CHAINE_CARACTERES" IS 'Valeur en chaine de caractères';
COMMENT ON COLUMN "FORMULAIRE"."TA_DONNEE"."NOMBRE_ENTIER" IS 'Valeur en nombre entier';
COMMENT ON COLUMN "FORMULAIRE"."TA_DONNEE"."AUDIT_IDENTIFIANT" IS 'Identifiant de l''audit';
COMMENT ON COLUMN "FORMULAIRE"."TA_DONNEE"."AUDIT_ACTEUR" IS 'Qui a fait';
COMMENT ON COLUMN "FORMULAIRE"."TA_DONNEE"."AUDIT_FONCTIONNALITE" IS 'La fonctionnalité faite';
COMMENT ON COLUMN "FORMULAIRE"."TA_DONNEE"."AUDIT_ACTION" IS 'Quoi a été fait sur la donnée';
COMMENT ON COLUMN "FORMULAIRE"."TA_DONNEE"."AUDIT_DATE" IS 'Quand cela a été fait';
COMMENT ON COLUMN "FORMULAIRE"."TA_DONNEE"."AUDIT_SESSION" IS 'Dans quelle session cela a été fait';

---------------------------------------------------------------------------------------------------
--- Audit -----------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------

CREATE SEQUENCE  "FORMULAIRE"."REVINFO_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 CACHE 5;