INSERT INTO TA_PLAN_COMPTABLE(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('1','1','1','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_BUDGET(IDENTIFIANT,CODE,LIBELLE,ECOLE,PLAN_COMPTABLE,ANNEE,STATUT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('toupdate','1','1','1','1',2025,'CREE','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO ECOLEVIEDBV2.ECOLE(ecoleid,ecolecode,ecoleclibelle) VALUES ('1','1','CSP Cocody');

-- Changement statut budget
INSERT INTO TA_BUDGET(IDENTIFIANT,CODE,LIBELLE,ECOLE,PLAN_COMPTABLE,ANNEE,STATUT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('transmit_when_created','transmit_when_created','1','1','1',2025,'CREE','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_BUDGET(IDENTIFIANT,CODE,LIBELLE,ECOLE,PLAN_COMPTABLE,ANNEE,STATUT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('accept_when_transmitted','accept_when_transmitted','1','1','1',2025,'TRANSMIS','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_BUDGET(IDENTIFIANT,CODE,LIBELLE,ECOLE,PLAN_COMPTABLE,ANNEE,STATUT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('approve_when_accepted','approve_when_accepted','1','1','1',2025,'ACCEPTE','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_BUDGET(IDENTIFIANT,CODE,LIBELLE,ECOLE,PLAN_COMPTABLE,ANNEE,STATUT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('return_when_transmistted','return_when_transmistted','1','1','1',2025,'TRANSMIS','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_BUDGET(IDENTIFIANT,CODE,LIBELLE,ECOLE,PLAN_COMPTABLE,ANNEE,STATUT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('return_when_accepted','return_when_accepted','1','1','1',2025,'ACCEPTE','1','1','1','CREATION',DATE '2000-1-1');