INSERT INTO TA_PLAN_COMPTABLE(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('1','1','1','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_BUDGET(IDENTIFIANT,CODE,LIBELLE,ECOLE,PLAN_COMPTABLE,ANNEE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('toupdate','1','1','1','1',2025,'1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO ECOLEVIEDBV2.ECOLE(ecoleid,ecolecode,ecoleclibelle) VALUES ('1','1','CSP Cocody');