INSERT INTO TA_FORMULAIRE(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('1','1','Inscription','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_FORMULAIRE(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('readone','readone','Inscription','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_DESCRIPTION_CHAMP(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('1','1','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_DESCRIPTION_CHAMP(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('2','2','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_DESCRIPTION_CHAMP(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('3','3','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_DESCRIPTION_CHAMP(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('4','4','1','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_CHAMP(IDENTIFIANT,FORMULAIRE,DESCRIPTION,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('1','1','2','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_CHAMP(IDENTIFIANT,FORMULAIRE,DESCRIPTION,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('2','1','3','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_CHAMP(IDENTIFIANT,FORMULAIRE,DESCRIPTION,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('readone','readone','1','1','1','1','CREATION',DATE '2000-1-1');