INSERT INTO TA_GENRE(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('M','M','Masculin','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_TYPE_AFFECTATION(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('1','1','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_TYPE_AFFECTATION(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('2','2','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_TYPE_AFFECTATION(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('3','3','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_TYPE_AFFECTATION(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('forupdate','forupdate','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_TYPE_AFFECTATION(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('forupdatewhenoptionaltrue','forupdatewhenoptionaltrue','1','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_ANCIENNETE(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('1','1','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_ANCIENNETE(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('2','2','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_ANCIENNETE(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('3','3','1','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_GROUPE_ECHEANCE(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('1','1','1','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_ECHEANCE(IDENTIFIANT,CODE,LIBELLE,GROUPE,ECOLE,DATE_,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('1','1','1','1','1',DATE '2000-1-1','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_RUBRIQUE(IDENTIFIANT,ECOLE,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('1','1','1','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_RUBRIQUE(IDENTIFIANT,ECOLE,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('2','1','2','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_RUBRIQUE(IDENTIFIANT,ECOLE,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('3','1','3','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_RUBRIQUE(IDENTIFIANT,ECOLE,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('4','1','4','1','1','1','1','CREATION',DATE '2000-1-1');

-- Scolarité

INSERT INTO TA_SCOLARITE(IDENTIFIANT,CODE,ECOLE,BRANCHE,PERIODE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('toupdate','toupdate','E','B','P','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_SCOLARITE(IDENTIFIANT,CODE,ECOLE,BRANCHE,PERIODE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('1','1','5','1','P','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_SCOLARITE(IDENTIFIANT,CODE,ECOLE,BRANCHE,PERIODE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('2','2','5','2','P','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_SCOLARITE(IDENTIFIANT,CODE,ECOLE,BRANCHE,PERIODE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('3','3','5','4','P','1','1','1','CREATION',DATE '2000-1-1');

-- Frais

INSERT INTO TA_MONTANT(IDENTIFIANT,VALEUR,VALEUR_INSCRIPTION,FACULTATIF,RECONDUCTIBLE,NUMERO_ORDRE_PAIEMENT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('toupdatefee',0,0,0,0,0,'1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_FRAIS(IDENTIFIANT,TYPE_AFFECTATION,ANCIENNETE,RUBRIQUE,SCOLARITE,MONTANT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('toupdate','1','3','1','1','toupdatefee','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_MONTANT(IDENTIFIANT,VALEUR,VALEUR_INSCRIPTION,FACULTATIF,RECONDUCTIBLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('toupdatewhenoptionaltrue',0,0,1,0,'1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_FRAIS(IDENTIFIANT,TYPE_AFFECTATION,ANCIENNETE,RUBRIQUE,SCOLARITE,MONTANT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('toupdatewhenoptionaltrue','forupdatewhenoptionaltrue','1','3','1','toupdatewhenoptionaltrue','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_MONTANT(IDENTIFIANT,VALEUR,VALEUR_INSCRIPTION,FACULTATIF,RECONDUCTIBLE,NUMERO_ORDRE_PAIEMENT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('1',100,0,0,0,0,'1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_FRAIS(IDENTIFIANT,TYPE_AFFECTATION,ANCIENNETE,RUBRIQUE,SCOLARITE,MONTANT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('1','1','1','1','1','1','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_MONTANT(IDENTIFIANT,VALEUR,VALEUR_INSCRIPTION,FACULTATIF,RECONDUCTIBLE,NUMERO_ORDRE_PAIEMENT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('2',200,50,0,0,0,'1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_FRAIS(IDENTIFIANT,TYPE_AFFECTATION,ANCIENNETE,RUBRIQUE,SCOLARITE,MONTANT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('2','1','1','1','2','2','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_MONTANT(IDENTIFIANT,VALEUR,VALEUR_INSCRIPTION,FACULTATIF,RECONDUCTIBLE,NUMERO_ORDRE_PAIEMENT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('3',300,25,0,0,0,'1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_FRAIS(IDENTIFIANT,TYPE_AFFECTATION,ANCIENNETE,RUBRIQUE,SCOLARITE,MONTANT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('3','1','1','2','2','3','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO TA_MONTANT(IDENTIFIANT,VALEUR,VALEUR_INSCRIPTION,FACULTATIF,RECONDUCTIBLE,NUMERO_ORDRE_PAIEMENT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('4',1000,500,1,0,0,'1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_FRAIS(IDENTIFIANT,TYPE_AFFECTATION,ANCIENNETE,RUBRIQUE,SCOLARITE,MONTANT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('4','1','1','3','2','4','1','1','1','CREATION',DATE '2000-1-1');

-- École
INSERT INTO ECOLEVIEDBV2.ECOLE(ecoleid,niveau_enseignement_id) VALUES (1,1);
INSERT INTO ECOLEVIEDBV2.ECOLE(ecoleid,niveau_enseignement_id) VALUES (2,1);
INSERT INTO ECOLEVIEDBV2.ECOLE(ecoleid,niveau_enseignement_id) VALUES (3,1);
INSERT INTO ECOLEVIEDBV2.ECOLE(ecoleid,niveau_enseignement_id) VALUES (4,1);
INSERT INTO ECOLEVIEDBV2.ECOLE(ecoleid) VALUES (5);

-- Année Scolaire
-- 		Central
INSERT INTO ECOLEVIEDBV2.ANNEE_SCOLAIRE(annee_scolaireid,annee,Niveau_Enseignement_id,niveau) VALUES (1,2020,1,'CENTRAL');
INSERT INTO ECOLEVIEDBV2.ANNEE_SCOLAIRE(annee_scolaireid,annee,Niveau_Enseignement_id,niveau) VALUES (2,2021,1,'CENTRAL');
INSERT INTO ECOLEVIEDBV2.ANNEE_SCOLAIRE(annee_scolaireid,annee,Niveau_Enseignement_id,niveau) VALUES (3,2022,1,'CENTRAL');
INSERT INTO ECOLEVIEDBV2.ANNEE_SCOLAIRE(annee_scolaireid,annee,Niveau_Enseignement_id,niveau) VALUES (4,2023,1,'CENTRAL');

-- 		Ecole 1
INSERT INTO ECOLEVIEDBV2.ANNEE_SCOLAIRE(annee_scolaireid,annee,ecole_id,statut) VALUES (5,2020,1,'FERME');
INSERT INTO ECOLEVIEDBV2.ANNEE_SCOLAIRE(annee_scolaireid,annee,ecole_id,statut) VALUES (6,2021,1,'FERME');
INSERT INTO ECOLEVIEDBV2.ANNEE_SCOLAIRE(annee_scolaireid,annee,ecole_id,statut) VALUES (7,2022,1,'OUVERT');

-- 		Ecole 2
INSERT INTO ECOLEVIEDBV2.ANNEE_SCOLAIRE(annee_scolaireid,annee,ecole_id,statut) VALUES (8,2020,2,'FERME');
INSERT INTO ECOLEVIEDBV2.ANNEE_SCOLAIRE(annee_scolaireid,annee,ecole_id,statut) VALUES (9,2021,2,'FERME');
INSERT INTO ECOLEVIEDBV2.ANNEE_SCOLAIRE(annee_scolaireid,annee,ecole_id,statut) VALUES (10,2022,2,'FERME');
INSERT INTO ECOLEVIEDBV2.ANNEE_SCOLAIRE(annee_scolaireid,annee,ecole_id,statut) VALUES (11,2023,2,'OUVERT');

-- 		Ecole 3
INSERT INTO ECOLEVIEDBV2.ANNEE_SCOLAIRE(annee_scolaireid,annee,ecole_id,statut) VALUES (12,2020,3,'FERME');
INSERT INTO ECOLEVIEDBV2.ANNEE_SCOLAIRE(annee_scolaireid,annee,ecole_id,statut) VALUES (13,2021,3,'FERME');
INSERT INTO ECOLEVIEDBV2.ANNEE_SCOLAIRE(annee_scolaireid,annee,ecole_id,statut) VALUES (14,2022,3,'OUVERT');
INSERT INTO ECOLEVIEDBV2.ANNEE_SCOLAIRE(annee_scolaireid,annee,ecole_id,statut) VALUES (15,2023,3,'OUVERT');

-- Programme
INSERT INTO ECOLEVIEDBV2.PROGRAMME(id) VALUES ('1');
INSERT INTO ECOLEVIEDBV2.PROGRAMME(id) VALUES ('2');
INSERT INTO ECOLEVIEDBV2.PROGRAMME(id) VALUES ('3');

-- Branche
INSERT INTO ECOLEVIEDBV2.BRANCHE(id,fk_programme_id,niveau_enseignement_id) VALUES (1,'1',1);
INSERT INTO ECOLEVIEDBV2.BRANCHE(id,fk_programme_id,niveau_enseignement_id) VALUES (2,'1',1);
INSERT INTO ECOLEVIEDBV2.BRANCHE(id,fk_programme_id,niveau_enseignement_id) VALUES (3,'1',1);
INSERT INTO ECOLEVIEDBV2.BRANCHE(id,fk_programme_id,niveau_enseignement_id) VALUES (4,'1',1);
INSERT INTO ECOLEVIEDBV2.BRANCHE(id,fk_programme_id,niveau_enseignement_id) VALUES (5,'1',1);
INSERT INTO ECOLEVIEDBV2.BRANCHE(id,fk_programme_id,niveau_enseignement_id) VALUES (6,'3',1);
INSERT INTO ECOLEVIEDBV2.BRANCHE(id,fk_programme_id,niveau_enseignement_id) VALUES (7,'3',1);

-- Programme école
INSERT INTO ECOLEVIEDBV2.PROGRAMME_ECOLE(id,fk_programme_id,fk_ecole_id) VALUES ('1','1',1);
INSERT INTO ECOLEVIEDBV2.PROGRAMME_ECOLE(id,fk_programme_id,fk_ecole_id) VALUES ('2','2',2);
INSERT INTO ECOLEVIEDBV2.PROGRAMME_ECOLE(id,fk_programme_id,fk_ecole_id) VALUES ('3','3',3);

-- Classe
INSERT INTO ECOLEVIEDBV2.CLASSE(classeid,ecole_ecoleid,branche_id,visible) VALUES (1,1,1,1);
INSERT INTO ECOLEVIEDBV2.CLASSE(classeid,ecole_ecoleid,branche_id,visible) VALUES (2,2,1,1);
INSERT INTO ECOLEVIEDBV2.CLASSE(classeid,ecole_ecoleid,branche_id,visible) VALUES (3,2,2,1);
INSERT INTO ECOLEVIEDBV2.CLASSE(classeid,ecole_ecoleid,branche_id,visible) VALUES (4,2,2,1);
INSERT INTO ECOLEVIEDBV2.CLASSE(classeid,ecole_ecoleid,branche_id,visible) VALUES (5,2,2,1);
INSERT INTO ECOLEVIEDBV2.CLASSE(classeid,ecole_ecoleid,branche_id,visible) VALUES (6,5,1,1);
INSERT INTO ECOLEVIEDBV2.CLASSE(classeid,ecole_ecoleid,branche_id,visible) VALUES (7,5,2,1);
INSERT INTO ECOLEVIEDBV2.CLASSE(classeid,ecole_ecoleid,branche_id,visible) VALUES (8,5,2,1);
