INSERT INTO TA_GENRE(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('M','M','Masculin','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_TYPE_AFFECTATION(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('1','1','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_ANCIENNETE(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('1','1','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_GROUPE_ECHEANCE(IDENTIFIANT,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('1','1','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_ECHEANCE(IDENTIFIANT,CODE,LIBELLE,GROUPE,ECOLE,DATE_,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('1','1','1','1','1',DATE '2000-1-1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_RUBRIQUE(IDENTIFIANT,ECOLE,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('1','1','1','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_RUBRIQUE(IDENTIFIANT,ECOLE,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('2','1','2','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_RUBRIQUE(IDENTIFIANT,ECOLE,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('3','1','3','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_RUBRIQUE(IDENTIFIANT,ECOLE,CODE,LIBELLE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('4','1','4','1','1','1','1','CREATION',DATE '2000-1-1');

-- Scolarité

INSERT INTO TA_SCOLARITE(IDENTIFIANT,CODE,ECOLE,BRANCHE,PERIODE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('toupdate','toupdate','E','B','P','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_SCOLARITE(IDENTIFIANT,CODE,ECOLE,BRANCHE,PERIODE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('1','1','5','1','P','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_SCOLARITE(IDENTIFIANT,CODE,ECOLE,BRANCHE,PERIODE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('2','2','5','2','P','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_SCOLARITE(IDENTIFIANT,CODE,ECOLE,BRANCHE,PERIODE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE)
VALUES ('3','3','5','4','P','1','1','1','CREATION',DATE '2000-1-1');


-- École
INSERT INTO ECOLEVIEDBV2.ECOLE(ecoleid,niveau_enseignement_id) VALUES (1,1);
INSERT INTO ECOLEVIEDBV2.ECOLE(ecoleid,niveau_enseignement_id) VALUES (2,1);
INSERT INTO ECOLEVIEDBV2.ECOLE(ecoleid,niveau_enseignement_id) VALUES (3,1);
INSERT INTO ECOLEVIEDBV2.ECOLE(ecoleid,niveau_enseignement_id) VALUES (4,1);
INSERT INTO ECOLEVIEDBV2.ECOLE(ecoleid) VALUES (5);

-- Programme
INSERT INTO ECOLEVIEDBV2.PROGRAMME(id) VALUES ('1');
INSERT INTO ECOLEVIEDBV2.PROGRAMME(id) VALUES ('2');
INSERT INTO ECOLEVIEDBV2.PROGRAMME(id) VALUES ('3');

-- Branche
INSERT INTO ECOLEVIEDBV2.BRANCHE(id,fk_programme_id,niveau_enseignement_id) VALUES (1,'1',1);
INSERT INTO ECOLEVIEDBV2.BRANCHE(id,fk_programme_id,niveau_enseignement_id) VALUES (2,'1',1);
INSERT INTO ECOLEVIEDBV2.BRANCHE(id,fk_programme_id,niveau_enseignement_id) VALUES (3,'1',1);
INSERT INTO ECOLEVIEDBV2.BRANCHE(id,fk_programme_id,niveau_enseignement_id) VALUES (4,'1',1);
INSERT INTO ECOLEVIEDBV2.BRANCHE(id,fk_programme_id,niveau_enseignement_id) VALUES (5,'1',1);
INSERT INTO ECOLEVIEDBV2.BRANCHE(id,fk_programme_id,niveau_enseignement_id) VALUES (6,'3',1);
INSERT INTO ECOLEVIEDBV2.BRANCHE(id,fk_programme_id,niveau_enseignement_id) VALUES (7,'3',1);

-- Programme école
INSERT INTO ECOLEVIEDBV2.PROGRAMME_ECOLE(id,fk_programme_id,fk_ecole_id) VALUES ('1','1',1);
INSERT INTO ECOLEVIEDBV2.PROGRAMME_ECOLE(id,fk_programme_id,fk_ecole_id) VALUES ('2','2',2);
INSERT INTO ECOLEVIEDBV2.PROGRAMME_ECOLE(id,fk_programme_id,fk_ecole_id) VALUES ('3','3',3);

-- Classe
INSERT INTO ECOLEVIEDBV2.CLASSE(classeid,ecole_ecoleid,branche_id,visible) VALUES (1,1,1,1);
INSERT INTO ECOLEVIEDBV2.CLASSE(classeid,ecole_ecoleid,branche_id,visible) VALUES (2,2,1,1);
INSERT INTO ECOLEVIEDBV2.CLASSE(classeid,ecole_ecoleid,branche_id,visible) VALUES (3,2,2,1);
INSERT INTO ECOLEVIEDBV2.CLASSE(classeid,ecole_ecoleid,branche_id,visible) VALUES (4,2,2,1);
INSERT INTO ECOLEVIEDBV2.CLASSE(classeid,ecole_ecoleid,branche_id,visible) VALUES (5,2,2,1);
INSERT INTO ECOLEVIEDBV2.CLASSE(classeid,ecole_ecoleid,branche_id,visible) VALUES (6,5,1,1);
INSERT INTO ECOLEVIEDBV2.CLASSE(classeid,ecole_ecoleid,branche_id,visible) VALUES (7,5,2,1);
INSERT INTO ECOLEVIEDBV2.CLASSE(classeid,ecole_ecoleid,branche_id,visible) VALUES (8,5,2,1);
