INSERT INTO TA_SCOLARITE(IDENTIFIANT,CODE,ECOLE,BRANCHE,PERIODE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('1','1','1','1','1','1','1','1','CREATION',DATE '2000-1-1');
INSERT INTO TA_SCOLARITE(IDENTIFIANT,CODE,ECOLE,BRANCHE,PERIODE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_FONCTIONNALITE,AUDIT_ACTION,AUDIT_DATE) VALUES ('2','2','unknown','unknown','unknown','1','1','1','CREATION',DATE '2000-1-1');

INSERT INTO VMA_ECOLE(IDENTIFIANT,LIBELLE) VALUES ('1','CSP Cocody');
INSERT INTO VMA_BRANCHE(IDENTIFIANT,LIBELLE) VALUES ('1','6ieme');
INSERT INTO VMA_PERIODE(IDENTIFIANT,LIBELLE) VALUES ('1','2023-2024');